### ISSUE TITLE
Error in fnxmgr.py - invalid escape sequence '\S'

### ISSUE THREAD

**Issue by SplitSpine** [pweingar/FoenixMgr#13]
I seem to get a error when running fnxmgr.

fnxmgr.py:180: SyntaxWarning: invalid escape sequence '\S'

even when running the command with only --list-ports

**Comment by pweingar** [comment]
Are you using the most recent update to the package? You might try pulling the most recent code from the repository, if not. That error message does not make any sense given the current code... line 180 of fnxmgr.py is just an `else` statement.

**Comment by SplitSpine** [comment]
PS f256_firmware_2023.5\firmware> python.exe --version
Python 3.12.1

PS f256_firmware_2023.5\firmware> python fnxmgr.zip
f256_firmware_2023.5\firmware\fnxmgr.zip\__main__.py:203: SyntaxWarning: invalid escape sequence '\S'
f256_firmware_2023.5\firmware\fnxmgr.zip\__main__.py:203: SyntaxWarning: invalid escape sequence '\S'
usage: fnxmgr.zip [-h] [--port PORT] [--list-ports] [--label-file LABEL_FILE] [--count COUNT] [--dump ADDRESS]
                  [--deref LABEL] [--lookup LABEL] [--revision] [--flash BINARY FILE] [--flash-sector NUMBER]
                  [--flash-bulk CSV FILE] [--binary BINARY FILE] [--copy COPY FILE] [--address ADDRESS]
                  [--upload HEX FILE] [--upload-wdc BINARY FILE] [--run-pgz PGZ FILE] [--run-pgx PGX FILE]
                  [--upload-srec SREC FILE] [--boot STRING] [--target STRING] [--tcp-bridge HOST:PORT]


I also tried to download from this GitHub, same error but just with line 180.

on my old windows 10 install, it worked fine, this one I'm on now is only 2-3 md old.

**Comment by pweingar** [comment]
I wonder if it's something to do with the Python version. I'm still running on 3.7. I'll update my install and see what happens. This error location makes more sense: it's a regular expression used for label lookup and retrieval and does in fact use the \S pattern. It may be that something about regular expression syntax has changed between 3.7 and 3.12.

**Comment by pweingar** [comment]
OK... I see the issue, I think. I should have used a raw string syntax there, and 3.12 is being more strict about it. I'll post an update for you to try in a moment.

**Comment by pweingar** [comment]
OK... The most recent commit should fix it. Let me know.

**Comment by SplitSpine** [comment]
lol. I just deleted everything Python and installed v.3.11.7. and it seems to work now.

**Comment by pweingar** [comment]
Shall I mark this as closed then? I _think_ it should work ok for you in 3.12 now.

**Comment by SplitSpine** [comment]
I'll run with 3.11 for now. Close it up.
